name: CI

on:
  push:
    branches:    
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: setup-node
      uses: actions/setup-node@v1
    - name: install dependencies
      run: npm install
    - name: lint project
      run: npm run lint
    - name: generate pages
      run: npm run generate
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@2.0.3
      env:
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist
